import PDFDocument from "pdfkit";
import * as fs from "fs";
import * as path from "path";

// ── Types ────────────────────────────────────────────────────────────────────

export type Severity = "CRITICAL" | "HIGH" | "MEDIUM" | "LOW" | "INFO";

export interface ScanFinding {
  id: string;
  title: string;
  description: string;
  severity: Severity;
  location?: string;
  line?: number;
  remediation?: string;
}

export interface ScanResult {
  target: string;
  scannedAt: string; // ISO 8601
  scannerVersion: string;
  findings: ScanFinding[];
  notes?: string;
}

export interface ReportOptions {
  outputPath: string;
}

// ── Helpers ──────────────────────────────────────────────────────────────────

const SEVERITY_ORDER: Severity[] = [
  "CRITICAL",
  "HIGH",
  "MEDIUM",
  "LOW",
  "INFO",
];

export function getOverallRisk(findings: ScanFinding[]): Severity | "NONE" {
  for (const sev of SEVERITY_ORDER) {
    if (findings.some((f) => f.severity === sev)) return sev;
  }
  return "NONE";
}

export function countBySeverity(
  findings: ScanFinding[],
  severity: Severity
): number {
  return findings.filter((f) => f.severity === severity).length;
}

export function sortFindingsBySeverity(findings: ScanFinding[]): ScanFinding[] {
  return [...findings].sort(
    (a, b) =>
      SEVERITY_ORDER.indexOf(a.severity) - SEVERITY_ORDER.indexOf(b.severity)
  );
}

// ── Report Generator ─────────────────────────────────────────────────────────

export async function generateScanReport(
  scan: ScanResult,
  options: ReportOptions
): Promise<void> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "A4" });

    const dir = path.dirname(options.outputPath);
    if (dir && !fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    const stream = fs.createWriteStream(options.outputPath);
    doc.pipe(stream);

    const overallRisk = getOverallRisk(scan.findings);
    const sorted = sortFindingsBySeverity(scan.findings);

    // ── Header ────────────────────────────────────────────────────────────
    doc
      .fontSize(20)
      .font("Helvetica-Bold")
      .text("VERO PROTOCOL — AUDIT REPORT", { align: "center" });

    doc.moveDown(0.5);
    doc
      .fontSize(10)
      .font("Helvetica")
      .text(`Target:           ${scan.target}`)
      .text(`Scanned at:       ${new Date(scan.scannedAt).toUTCString()}`)
      .text(`Scanner version:  ${scan.scannerVersion}`);

    doc.moveDown(0.3);
    doc
      .fontSize(12)
      .font("Helvetica-Bold")
      .text(`Overall risk: ${overallRisk}`);

    doc.moveDown(1);

    // ── Summary ───────────────────────────────────────────────────────────
    doc.fontSize(14).font("Helvetica-Bold").text("SUMMARY");
    doc.moveDown(0.3);

    for (const sev of SEVERITY_ORDER) {
      const count = countBySeverity(scan.findings, sev);
      doc
        .fontSize(10)
        .font("Helvetica")
        .text(`  ${sev.padEnd(10)} ${count}`);
    }

    doc
      .fontSize(10)
      .font("Helvetica-Bold")
      .text(`  ${"TOTAL".padEnd(10)} ${scan.findings.length}`);

    doc.moveDown(1);

    // ── Findings ──────────────────────────────────────────────────────────
    doc.fontSize(14).font("Helvetica-Bold").text("FINDINGS");
    doc.moveDown(0.5);

    if (sorted.length === 0) {
      doc
        .fontSize(10)
        .font("Helvetica")
        .text("  No findings detected.", { color: "green" } as any);
    }

    for (const finding of sorted) {
      // Add a new page if close to bottom
      if (doc.y > 700) doc.addPage();

      doc
        .fontSize(10)
        .font("Helvetica-Bold")
        .text(`[${finding.severity}] ${finding.id} — ${finding.title}`);

      doc
        .fontSize(9)
        .font("Helvetica")
        .text(`  ${finding.description}`, { width: 490 });

      if (finding.location) {
        const loc = finding.line
          ? `${finding.location}:${finding.line}`
          : finding.location;
        doc.text(`  Location: ${loc}`);
      }

      if (finding.remediation) {
        doc.text(`  Remediation: ${finding.remediation}`, { width: 490 });
      }

      doc.moveDown(0.5);
    }

    // ── Notes ─────────────────────────────────────────────────────────────
    if (scan.notes) {
      if (doc.y > 700) doc.addPage();
      doc.moveDown(0.5);
      doc.fontSize(14).font("Helvetica-Bold").text("NOTES");
      doc.moveDown(0.3);
      doc.fontSize(9).font("Helvetica").text(scan.notes, { width: 490 });
    }

    // ── Footer ────────────────────────────────────────────────────────────
    doc
      .fontSize(8)
      .font("Helvetica")
      .text(
        "Generated by vero-audit-guard — Vero Protocol",
        50,
        doc.page.height - 40,
        { align: "center", width: doc.page.width - 100 }
      );

    doc.end();

    stream.on("finish", resolve);
    stream.on("error", reject);
  });
}
